language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.0
env:
  - VIDEOBARN_SIGNUP_TOKEN="letmesignupplz" VIDEOBARN_SECRET_TOKEN="60ed4add5c73ac6c4d372c696b1c27977fc44535e0afd87e09ceb000dfb2819b251f746a403be2d8a5bc15904858ad7cabe7eacf9c0ff9a47b4084280d1eca36"
before_script:
  - "cp ./config/database.travis.yml ./config/database.yml"
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake